# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import config_server_utils.config_server_pb2 as config__server__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in config_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddIP = channel.unary_unary(
                '/IPService/AddIP',
                request_serializer=config__server__pb2.IPRequest.SerializeToString,
                response_deserializer=config__server__pb2.Response.FromString,
                _registered_method=True)
        self.RemoveIP = channel.unary_unary(
                '/IPService/RemoveIP',
                request_serializer=config__server__pb2.IPRequest.SerializeToString,
                response_deserializer=config__server__pb2.Response.FromString,
                _registered_method=True)
        self.GetIPs = channel.unary_unary(
                '/IPService/GetIPs',
                request_serializer=config__server__pb2.ServiceRequest.SerializeToString,
                response_deserializer=config__server__pb2.IPList.FromString,
                _registered_method=True)


class IPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIPs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddIP': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIP,
                    request_deserializer=config__server__pb2.IPRequest.FromString,
                    response_serializer=config__server__pb2.Response.SerializeToString,
            ),
            'RemoveIP': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveIP,
                    request_deserializer=config__server__pb2.IPRequest.FromString,
                    response_serializer=config__server__pb2.Response.SerializeToString,
            ),
            'GetIPs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIPs,
                    request_deserializer=config__server__pb2.ServiceRequest.FromString,
                    response_serializer=config__server__pb2.IPList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('IPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IPService/AddIP',
            config__server__pb2.IPRequest.SerializeToString,
            config__server__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IPService/RemoveIP',
            config__server__pb2.IPRequest.SerializeToString,
            config__server__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIPs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IPService/GetIPs',
            config__server__pb2.ServiceRequest.SerializeToString,
            config__server__pb2.IPList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
