# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'config_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfig_server.proto\"(\n\tIPRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"!\n\x0eServiceRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x15\n\x06IPList\x12\x0b\n\x03ips\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2r\n\tIPService\x12\x1e\n\x05\x41\x64\x64IP\x12\n.IPRequest\x1a\t.Response\x12!\n\x08RemoveIP\x12\n.IPRequest\x1a\t.Response\x12\"\n\x06GetIPs\x12\x0f.ServiceRequest\x1a\x07.IPListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IPREQUEST']._serialized_start=23
  _globals['_IPREQUEST']._serialized_end=63
  _globals['_SERVICEREQUEST']._serialized_start=65
  _globals['_SERVICEREQUEST']._serialized_end=98
  _globals['_IPLIST']._serialized_start=100
  _globals['_IPLIST']._serialized_end=121
  _globals['_RESPONSE']._serialized_start=123
  _globals['_RESPONSE']._serialized_end=150
  _globals['_IPSERVICE']._serialized_start=152
  _globals['_IPSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
